### ISSUE TITLE
Different home directory permissions now possible.

### ISSUE THREAD

**Issue by robertdebock** [torrancew/puppet-account#45]
The default 0750 permission is used. This is a pretty good set, but might need to be set differently.

Here is the code that sets this permission is a "static" way in init.pp
```
  file {
    "${title}_home":
      ensure  => $dir_ensure,
      path    => $home_dir_real,
      owner   => $dir_owner,
      group   => $dir_group,
      mode    => 0750;
```

I would like to be able to overwrite this setting with hiera, something like this:
```
accounts:
  exampleuser:
    home_dir: /home/exampleuser
    homedirpermission: 0700
```
