### ISSUE TITLE
User group creation support

### ISSUE THREAD

**Issue by gothicx** [torrancew/puppet-account#55]
It would be good if this module could support the creation of groups with a specific gid. In the module users, it's already possible to assign users to pre-existing groups.

```
accounts::users:
   account1:
      groups:
         - group1
         - group2
accounts::groups:
  staff:
    gid: 1500
    comment: 'staff group'
```
